### ISSUE TITLE
[Bug]: http api, The KNN topN parameter can be filled with float type without error.

### ISSUE THREAD

**Issue by TiNnNnnn** [infiniflow/infinity#1034]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main 

### Commit ID

[1d3a04c](https://github.com/infiniflow/infinity/commit/1d3a04c3159c48cc07490935a273b6d8b3ac8852)

### Other environment information

```Markdown
Linxu Ubuntu 23.04
```

### Actual behavior

The KNN topN parameter can be filled with float type without error.

### Expected behavior

The KNN topN parameter can't  be filled with float type 

### Steps to reproduce

```Markdown
run function: test_various_topn in test_knn.py ,you can add a num in format of "float" to topn list,and run again,it not lead any error resp
```

**Comment by JinHai-CN** [comment]
Fixed
