### ISSUE TITLE
[Feature Request]: Save block version as a disk file.

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#1042]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Block version information is in catalog now, which may cost lots of memory. Currently, catalog file is loaded totally when the system starts.
```

### Describe the feature you'd like

We propose to store block version information into a file, but not in catalog.  

### Describe implementation you've considered

Similar solution as block column data.

**Comment by lyssom** [comment]
Hello, I'm a newbie in the community and I'd like to try this issue. But I want some help. Now, I seeBlockVersion::SaveToFile is write to a file not catalog. How can I understand "store block version information into a file". And where can I got some " solution as block column data solution as block column data" refer. Thanks

**Comment by lyssom** [comment]
Hello, I'm a newbie in the community and I'd like to try this issue. But I want some help. Now, I seeBlockVersion::SaveToFile is write to a file not catalog. How can I understand "store block version information into a file". And where can I got some " block column data solution" refer. Thanks

**Comment by JinHai-CN** [comment]
@lyssom 

Your understanding is correct, the current version file can now be stored on the disk. However, this file is currently considered as part of the catalog. We can see that the BlockEntry:: Deserialize function directly reads the version file. 

We have conducted some tests before, and when a large amount of data is inserted into infinity, this version file will occupy a lot of memory in memory. 

Perhaps the initial description of this issue led you to misunderstandings. The purpose of this issue is to manage version files like block column files using a buffer manager. Use pointers like buffer objects for reading and writing. Behind the Buffer Manager is a component that can manage global objects within the database

**Comment by lyssom** [comment]
ok
