### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by PandaWannaSleep** [infiniflow/infinity#1067]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

How about adding a hint of prerequisites of RAM and CPU in readme?
Building infinity from source seems costs more than 8G RAM even after I reduce the number of parallel compilations by "ninja -j1".
Building process crashes several times during my first exploration for infinity.

**Comment by JinHai-CN** [comment]
Good point.

we can compile normally in 16C and 16GB development environments. If we only compile the infinity target, it usually takes no more than 4 minutes. What is your development environment?

**Comment by PandaWannaSleep** [comment]
I have tried to build infinity in [16C 8GB] and [16C 4GB] on ubuntu20.04. 
Only [16C 8GB] with closed parallel compilations finally work through.

**Comment by JinHai-CN** [comment]
Thank you for your information.
