### ISSUE TITLE
[Bug]: http api: insert vector with type of integer will lead to bad resp 

### ISSUE THREAD

**Issue by TiNnNnnn** [infiniflow/infinity#1085]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

0

### Actual behavior

run test_http_insert_with_invalid_data_type in file:test_insert

### Expected behavior

reponse with no error

### Steps to reproduce

```Markdown
run test_http_insert_with_invalid_data_type in file:test_insert
table:
`self.create_table(db_name, table_name, {
            "c1": {"type": "integer", },
            "c2": {
                "type": "vector",
                "dimension": 3,
                "element_type": "integer",
            }
        })`
while inserting `[{'c1':1,'c2':[1,2,3]},{'c1':1,'c2':[1,2,3]}] `,it will lead a bad reponse with error_status = 500.
```

### Additional information
- insert vector with type of float lead no error
_No response_

**Comment by Ognimalf** [comment]
Fixed.
