### ISSUE TITLE
[Bug]: Decrease row count exceed actual row count@src/storage/meta/entry/segment_entry.cppm:184

### ISSUE THREAD

**Issue by Ziyan2019** [infiniflow/infinity#1087]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

current

### Actual behavior

tables with a vector column will encounter the bug when insert and delete parallelly. tables only contain basic datatype(int, float) run properly.

### Steps to reproduce

```Markdown
python -k test_insert_delete_update_parallel_vec python/parallel_test
```

**Comment by yuzhichang** [comment]
Duplicated with #161.
