### ISSUE TITLE
[Bug]: http api,the import option header is actually always false

### ISSUE THREAD

**Issue by TiNnNnnn** [infiniflow/infinity#1090]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

0

### Actual behavior

-

### Expected behavior

-

### Steps to reproduce

```Markdown
see file http_server.cpp ,in function: Import

you can see : " import_statement->header_ = false; "
```

### Additional information
- thera is no test for this in http

_No response_

**Comment by JinHai-CN** [comment]
fixed
