### ISSUE TITLE
[Question]: Does fulltext index support Chinese?

### ISSUE THREAD

**Issue by yc-huang** [infiniflow/infinity#1102]
### Describe your problem

searching a full-text index might failed when query contain Chinese, e.g.
`table.output(["*"]).match('body', '中', 'topn=2').to_pl()`
will throw error:

> 
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[31], line 1
----> 1 table.output(["*"]).match('body', '中', 'topn=2').to_pl()

File ~/miniconda3/envs/sammo/lib/python3.11/site-packages/infinity/remote_thrift/table.py:391, in RemoteTable.to_pl(self)
    390 def to_pl(self):
--> 391     return self.query_builder.to_pl()

File ~/miniconda3/envs/sammo/lib/python3.11/site-packages/infinity/remote_thrift/query_builder.py:239, in InfinityThriftQueryBuilder.to_pl(self)
    238 def to_pl(self) -> pl.DataFrame:
--> 239     return pl.from_pandas(self.to_df())

File ~/miniconda3/envs/sammo/lib/python3.11/site-packages/infinity/remote_thrift/query_builder.py:231, in InfinityThriftQueryBuilder.to_df(self)
    229 def to_df(self) -> pd.DataFrame:
    230     df_dict = {}
--> 231     data_dict, data_type_dict = self.to_result()
    232     for k, v in data_dict.items():
    233         data_series = pd.Series(
    234             v, dtype=logic_type_to_dtype(data_type_dict[k]))

File ~/miniconda3/envs/sammo/lib/python3.11/site-packages/infinity/remote_thrift/query_builder.py:227, in InfinityThriftQueryBuilder.to_result(self)
    219 query = Query(
    220     columns=self._columns,
    221     search=self._search,
   (...)
    224     offset=self._offset
    225 )
    226 self.reset()
--> 227 return self._table._execute_query(query)

File ~/miniconda3/envs/sammo/lib/python3.11/site-packages/infinity/remote_thrift/table.py:415, in RemoteTable._execute_query(self, query)
    413     return build_result(res)
    414 else:
--> 415     raise Exception(f"ERROR:{res.error_code}, {res.error_msg}")

Exception: ERROR:3052, Trying to match: 中 on fields: body failed.@src/executor/operator/physical_match.cpp:425@src/scheduler/fragment_context.cpp:1091

>

**Comment by yingfeng** [comment]
Yes, it support through `Jieba` analyzer. You need to clone [resource](https://github.com/infiniflow/resource) repo into some specified places according to config(by default, it's `/var/infinity` ) 
Currently there are some configuration bugs which will be fixed before 0.1 release

**Comment by yuzhichang** [comment]
Chinese support is ready. [Here]( https://github.com/infiniflow/infinity/blob/b79a770263cb607d8772d9d70e8ae22ae1911226/python/hello_infinity.py#L108)  is the sample code.
