### ISSUE TITLE
API CALLS

### ISSUE THREAD

**Issue by Scoutink** [infiniflow/infinity#1151]
### Describe your problem

Not sure how naïve the question is but I am asking for a specific project:

Will I be able to post data to knowledgebase and get responses via an API? I want to create a form where each field gets field_data via a prompt it sends to Ragflow with a certain knowledge base id/name to get information from. Once I click generate button, all form fields will send their prompts and receive the data.

**Comment by JinHai-CN** [comment]
> ### Describe your problem
> Not sure how naïve the question is but I am asking for a specific project:
> 
> Will I be able to post data to knowledgebase and get responses via an API? I want to create a form where each field gets field_data via a prompt it sends to Ragflow with a certain knowledge base id/name to get information from. Once I click generate button, all form fields will send their prompts and receive the data.

I suppose you are talking about RAGFlow, but not Infinity. Infinity is a database which can be used in RAG application. RAGFlow is a RAG framework can work as a knowledge base. You can use the API of RAGFlow conversation API to get what you want according the prompt.

If you have further question, we can talk about this topic in RAGFlow repository.

**Comment by Scoutink** [comment]
> If you have further question, we can talk about this topic in RAGFlow repository.

I think unintentionally I posted this on the wrong repo. I will post there once I start working on this. Thank you for the feedback.
