### ISSUE TITLE
[Feature Request]: Supports cosine similarity

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#1176]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Currently, infinity's vector search already supports Euclidean distance and inner product computation. The goal of this feature request is to allow infinity to support cosine similarity.

**Comment by yingfeng** [comment]
Notes: a parameter of "threshold" is required during retrieval such that results under the threshold would not be returned

**Comment by TangSiyang2001** [comment]
I'd like to have a try.

**Comment by JinHai-CN** [comment]
Fixed by #1343
