### ISSUE TITLE
[Doc]: Incorrect README for python-infinity

### ISSUE THREAD

**Issue by niebayes** [infiniflow/infinity#1200]
The README of the python SDK python-infinity is incorrect. The column definitions of the table `my_table` state that there're two columns named `c1` and `c2`, respectively. However, the subsequent insertions requires the table having columns `num`, `body`, and `vec`.

**Comment by niebayes** [comment]
I'd like to fix this issue.

**Comment by JinHai-CN** [comment]
> I'd like to fix this issue.

OK, thanks you.

**Comment by JinHai-CN** [comment]
Fixed by #1280
