### ISSUE TITLE
[Bug]: COUNT(*) cannot find table ref

### ISSUE THREAD

**Issue by small-turtle-1** [infiniflow/infinity#1211]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

c56ef5b

### Actual behavior and How to reproduce it

run such sql:
```sql
CREATE TABLE test_compact_big (c1 INTEGER, c2 BOOLEAN);
COPY test_compact_big FROM '/var/infinity/test_data//test_compact_big.csv' WITH ( DELIMITER ',' );
DELETE FROM test_compact_big WHERE c2 = False;
SELECT COUNT(*) FROM test_compact_big WHERE c2 = False;
```
throw unrecoverable error:
TableRef not found!@src/executor/physical_operator.cpp:49

**Comment by JinHai-CN** [comment]
Fixed
