### ISSUE TITLE
[Feature Request]: Support string for secondary index

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/infinity#1235]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Currently, secondary index only supports numeric fields which could be built based on PGM index.  String columns are also needed within secondary index for column filtering.
```

### Describe the feature you'd like

Both real time and offline index building are required to be supported.

**Comment by yingfeng** [comment]
String index could be built based on current secondary index through a hashing mechanism

String index is only used for equal filtering

**Comment by wuxiaobai24** [comment]
Hello, I am very interested in this project and would like to try to solve this issue. Can you assign the issue to me?

**Comment by yingfeng** [comment]
Sure, thanks for your interests!
