### ISSUE TITLE
[Feature Request]: Supporting query string escaping for full text search.

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/infinity#1266]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Currently, the full text search syntax does not have a query string escaping mechanism, for example within issue #1265 , '-' within the query string `DS-K3AJ303/Dm140` is parsed as NOT query statement which leads to execution error. 

We need to support query string escaping mechanism.

### Describe implementation you've considered

We need to support escaping query string, just like what [elasticsearch has done](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html).

**Comment by yuzhichang** [comment]
Fixed by https://github.com/infiniflow/infinity/pull/1303

Special characters in query should be escaped by users.
