### ISSUE TITLE
call BeginTxn multi times

### ISSUE THREAD

**Issue by xiaoma20082008** [infiniflow/infinity#1276]
## Is there an existing issue for the same bug?
 - [x] I have checked the existing issues.

## Version or Commit ID
a75522180bfbe6da57154f567cd23b0e479c1efb

## Other environment information
No response

## Actual behavior and How to reproduce it

https://github.com/infiniflow/infinity/blob/a75522180bfbe6da57154f567cd23b0e479c1efb/src/main/query_context.cpp#L120

https://github.com/infiniflow/infinity/blob/a75522180bfbe6da57154f567cd23b0e479c1efb/src/main/query_context.cpp#L125

## Expected behavior

remove the duplicated code

## Additional information
No response

**Comment by JinHai-CN** [comment]
Fixed.
