### ISSUE TITLE
[Bug]: Records that have been deleted can still be  obtained during match query

### ISSUE THREAD

**Issue by GuangchaoDeng** [infiniflow/infinity#1281]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.1.0/v0.1.1

### Actual behavior and How to reproduce it

1 插入记录，进行match查询，返回结果正常
2 删除插入记录，并再重新插入记录
3 进行match查询，已经删除的记录会被查询出

**Comment by JinHai-CN** [comment]
Fixed.
