### ISSUE TITLE
[Bug]: Can not use Infinity in windows docker-desktop with the command in readme.

### ISSUE THREAD

**Issue by Jack0Chan** [infiniflow/infinity#1350]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

0.2.0

### Other environment information

```Markdown
Windows 10
Docker Engine v25.0.3

conda create -n ifnty python=3.10
conda activate ifnty
pip3 install infinity-sdk==0.2.0.dev7
```

### Actual behavior and How to reproduce it

The command to run the docker container in README does not support for windows because the `--network=host` option is not fully supported in windows. The original command is

```docker run -d --name infinity -v /var/infinity/:/var/infinity --ulimit nofile=500000:500000 --network=host infiniflow/infinity:nightly```

The testing code will print: `Could not connect to any of [('127.0.0.1', 23817)]` by `infinity.connect(REMOTE_HOST)`.

### Expected behavior

The following command can make it work for windows, which removes `--network=host`, and adds port reflection `-p 23817:23817 -p 23820:23820 `:

```docker run -d --name infinity -v /var/infinity/:/var/infinity --ulimit nofile=500000:500000 -p 23817:23817 -p 23820:23820 infiniflow/infinity:nightly```

With this setup in windows, the following test code works.

### Additional information

Test code:

```python
import infinity
import infinity.index as index
from infinity.common import REMOTE_HOST, LOCAL_HOST
from infinity.common import ConflictType

infinity_obj = infinity.connect(REMOTE_HOST)
db = infinity_obj.get_database("default_db")
# Drop my_table if it already exists
db.drop_table("my_table", ConflictType.Ignore)
# Create a table named "my_table"
table = db.create_table("my_table", {"num": {"type": "integer"}, "body": {"type": "varchar"}, "vec": {"type": "vector, 4, float"}})
table.insert([
    {"num": 1, "body": "unnecessary and harmful", "vec": [1.0, 1.2, 0.8, 0.9]}])
table.insert([{"num": 2, "body": "Office for Harmful Blooms", "vec": [4.0, 4.2, 4.3, 4.5]}])
res = table.output(["*"]).knn("vec", [3.0, 2.8, 2.7, 3.1], "float", "ip", 2).to_pl()
print(res)```

**Comment by Jack0Chan** [comment]
I don't have MacOS x86_64, which may have the same problem as Windows.

**Comment by JinHai-CN** [comment]
Yes, we didn't test infinity on Windows before. Thank you for your testing, and we will follow your method to run infinity docker on windows.

**Comment by JinHai-CN** [comment]
Follow below instruction, infinity can run on Windows.

https://github.com/infiniflow/infinity/blob/main/docs/getstarted/deploy_infinity_server.mdx#deploy-infinity-using-docker
