### ISSUE TITLE
[Feature Request]: More examples are needed.

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#1490]
### Describe what you'd like

We need more examples to show how to use tensor data search, tensor data reranker and structured data filter.

1. Tensor data search. https://github.com/infiniflow/infinity/blob/main/example/tensor_search.py
2. Structured data filter. https://github.com/infiniflow/infinity/blob/main/example/filter_data.py
3. More complex hybrid search: https://github.com/infiniflow/infinity/blob/main/example/hybrid_search.py

Python SDK documents also need to update due to tensor and sparse data, index and search parameter.

**Comment by bash99** [comment]
And Please don't use fake data for sparse/tense vector.

Just use some small embedding model to encode data.

**Comment by JinHai-CN** [comment]
> And Please don't use fake data for sparse/tense vector.
> 
> Just use some small embedding model to encode data.

Ok, we will also provide some examples using real data.
