### ISSUE TITLE
[Bug]: Cannot conduct tensor search without launching a separate Infinity server. 

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/infinity#1501]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.2.1

### Actual behavior and How to reproduce it

See PR https://github.com/infiniflow/infinity/pull/1499 and use `infinity_instance = infinity.connect("/var/infinity")` instead of ` infinity_instance = infinity.connect(infinity.common.LOCAL_HOST)`

### Additional information

```
UnrecoverableException Can't cast from Boolean to Tensor(float,4)@src/function/cast/bool_cast.cppm:71
User defined signal 1
```

**Comment by yangzq50** [comment]
I wonder if this problem still exists in v0.3.0-dev1?

**Comment by writinwaters** [comment]
The issue is put to rest in v0.3.0-dev1. Thanks.
