### ISSUE TITLE
[Bug]: pip install failed

### ISSUE THREAD

**Issue by AInseven** [infiniflow/infinity#1512]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

infinity-sdk==0.2.1

### Other environment information

```Markdown
os:windows 11
```

### Actual behavior and How to reproduce it

pip install infinity-sdk==0.2.1
ERROR: Could not find a version that satisfies the requirement infinity-sdk==0.2.1 (from versions: 0.1.0.dev1, 0.1.0.dev2, 0.1.0.dev3, 0.1.0.dev4, 0.1.0.dev5, 0.1.0.dev6, 0.1.0.dev7, 0.1.0.dev8, 0.1.0.dev9, 0.1.0.dev10, 0.1.0.dev11, 0.1.0.dev12, 0.1.0.dev13, 0.1.0.dev14, 0.1.0.dev15, 0.1.0.dev16, 0.1.0.dev17, 0.1.0.dev18, 0.1.0.dev19, 0.1.0.dev20, 0.1.0.dev21, 0.1.0.dev22, 0.1.0, 0.1.1, 0.2.0.dev1, 0.2.0.dev2, 0.2.0.dev3, 0.2.0.dev4, 0.2.0.dev5, 0.2.0.dev6, 0.2.0.dev7)
ERROR: No matching distribution found for infinity-sdk==0.2.1

**Comment by JinHai-CN** [comment]
Infinity SDK needs linux environment, you can install WSL on Windows11 to run infinity SDK.

**Comment by AInseven** [comment]
Thanks.
