### ISSUE TITLE
[Bug]: Infinity crashes when building fulltext index using standard analyzer on chinese text column

### ISSUE THREAD

**Issue by yangzq50** [infiniflow/infinity#1533]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.3.0-dev2

### Actual behavior and How to reproduce it

Create fulltext index on varchar column with standard analyzer
Insert chinese text into the table, for example "<欧姆贝>,<类型>,<动物>"

**Comment by miguelwon** [comment]
I'm having a similar problem. My kernel crashes when building fulltext index of a 9M dataset. The problem is that it does not manages the memory and runs out of it (I'm working with a 30GB ram, so not really short on memory).

**Comment by JinHai-CN** [comment]
This issue is resolved before 0.3.0 is released. So your problems must be another issue. Would you please attached the dataset you are using? I want to reproduce the issue.

**Comment by miguelwon** [comment]
@JinHai-CN  do you have a huggingface user? I just created an org and will upload a private dataset to it. I will add you as member so that you can load the dataset. This is the code I used 

```
infinity_obj = infinity.connect("/home/ubuntu/justina/infinity")

#create the db and table
db_object = infinity_obj.create_database("justina_db")
table_object = db_object.create_table("justina_chunks", {
    "acordao_id": {"type": "varchar"}, 
    "chunk": {"type": "varchar"}, 
    "chunk_idx": {"type": "int"},
    "n_chunks": {"type": "int"},
    "tribunal": {"type": "varchar"}, 
    "url": {"type": "varchar"}, 
    "n_processo": {"type": "varchar"}, 
    "relator1": {"type": "int","default" : -1}, 
    "relator2": {"type": "int","default" : -1}, 
    "relator3": {"type": "int","default" : -1}, 
    "relator4": {"type": "int","default" : -1}, 
    "relator5": {"type": "int","default" : -1}, 
    "data_acordao": {"type": "float"}, 
    "chunk_id": {"type": "varchar"}, 
    "idx": {"type": "integer"}, 
    "dense_int8": {"type": "vector, 1024, int8"},
    "sparse": {"type": "sparse,250002,float,int"}, # 250002 is the vocab size of the tokenizer
    })
    
    #populate (had to inset one by one, because of error when insert in batches of 1000)
    relator2id = {}
with open('/home/ubuntu/data/data2vespa_bge_m3_ft_v2_chunks_dgsi_256_new/chunks256new_feedvespa.jsonl', 'r') as f:
    to_insert = []
    for i,line in tqdm(enumerate(f),total = 9_520_308):
        data = json.loads(line)
        del(data["descritores"])
        del(data["dense_binary"])
        data["sparse"] = {int(k): v for k, v in data["sparse"].items() if v > 0}
        if not data["sparse"]:
            continue
        idx = 0
        for rel in data["relator"]:
            rel = rel.strip()
            if rel:
                if rel not in relator2id:
                    relator2id[rel] = len(relator2id)                
                rel_id = relator2id[rel]
                if idx == 0:
                    data["relator1"] = rel_id
                elif idx == 1:
                    data["relator2"] = rel_id
                elif idx == 2:
                    data["relator3"] = rel_id
                elif idx == 3:
                    data["relator4"] = rel_id
                elif idx == 4:
                    data["relator5"] = rel_id
                idx += 1
        del(data["relator"])
        table_object.insert([data])
        # to_insert.append(data)
        # # insert data in batches of 1000
        # if len(to_insert) == 1000:
        #     table_object.insert(to_insert)
        #     to_insert = []

```

Then the BM25 index creation that crashes:

```
res = table_object.create_index(
        "bm25",
        IndexInfo("chunk", infinity.index.IndexType.FullText, {"ANALYZER": "standard"}), 
        ConflictType.Error)
res
```

Meanwhile I also tried a hnsw index that crashed also:

```

res = table_object.create_index(
    "hnsw",
    IndexInfo("dense_int8", IndexType.Hnsw, {"metric": "cosine"}), 
    ConflictType.Error)
res

```


I tried all these steps with a 1M sample and it works nicely.

**Comment by JinHai-CN** [comment]
> @JinHai-CN do you have a huggingface user? I just created an org and will upload a private dataset to it. I will add you as member so that you can load the dataset. This is the code I used
> 
> ```
> infinity_obj = infinity.connect("/home/ubuntu/justina/infinity")
> 
> #create the db and table
> db_object = infinity_obj.create_database("justina_db")
> table_object = db_object.create_table("justina_chunks", {
>     "acordao_id": {"type": "varchar"}, 
>     "chunk": {"type": "varchar"}, 
>     "chunk_idx": {"type": "int"},
>     "n_chunks": {"type": "int"},
>     "tribunal": {"type": "varchar"}, 
>     "url": {"type": "varchar"}, 
>     "n_processo": {"type": "varchar"}, 
>     "relator1": {"type": "int","default" : -1}, 
>     "relator2": {"type": "int","default" : -1}, 
>     "relator3": {"type": "int","default" : -1}, 
>     "relator4": {"type": "int","default" : -1}, 
>     "relator5": {"type": "int","default" : -1}, 
>     "data_acordao": {"type": "float"}, 
>     "chunk_id": {"type": "varchar"}, 
>     "idx": {"type": "integer"}, 
>     "dense_int8": {"type": "vector, 1024, int8"},
>     "sparse": {"type": "sparse,250002,float,int"}, # 250002 is the vocab size of the tokenizer
>     })
>     
>     #populate (had to inset one by one, because of error when insert in batches of 1000)
>     relator2id = {}
> with open('/home/ubuntu/data/data2vespa_bge_m3_ft_v2_chunks_dgsi_256_new/chunks256new_feedvespa.jsonl', 'r') as f:
>     to_insert = []
>     for i,line in tqdm(enumerate(f),total = 9_520_308):
>         data = json.loads(line)
>         del(data["descritores"])
>         del(data["dense_binary"])
>         data["sparse"] = {int(k): v for k, v in data["sparse"].items() if v > 0}
>         if not data["sparse"]:
>             continue
>         idx = 0
>         for rel in data["relator"]:
>             rel = rel.strip()
>             if rel:
>                 if rel not in relator2id:
>                     relator2id[rel] = len(relator2id)                
>                 rel_id = relator2id[rel]
>                 if idx == 0:
>                     data["relator1"] = rel_id
>                 elif idx == 1:
>                     data["relator2"] = rel_id
>                 elif idx == 2:
>                     data["relator3"] = rel_id
>                 elif idx == 3:
>                     data["relator4"] = rel_id
>                 elif idx == 4:
>                     data["relator5"] = rel_id
>                 idx += 1
>         del(data["relator"])
>         table_object.insert([data])
>         # to_insert.append(data)
>         # # insert data in batches of 1000
>         # if len(to_insert) == 1000:
>         #     table_object.insert(to_insert)
>         #     to_insert = []
> ```
> 
> Then the BM25 index creation that crashes:
> 
> ```
> res = table_object.create_index(
>         "bm25",
>         IndexInfo("chunk", infinity.index.IndexType.FullText, {"ANALYZER": "standard"}), 
>         ConflictType.Error)
> res
> ```
> 
> Meanwhile I also tried a hnsw index that crashed also:
> 
> ```
> 
> res = table_object.create_index(
>     "hnsw",
>     IndexInfo("dense_int8", IndexType.Hnsw, {"metric": "cosine"}), 
>     ConflictType.Error)
> res
> ```
> 
> I tried all these steps with a 1M sample and it works nicely.

HF: https://huggingface.co/jinhai-2012

**Comment by JinHai-CN** [comment]
@miguelwon Received the message, but when I accept the invitation, I got message from huggingface: "This invitation is invalid or expired".

**Comment by yangzq50** [comment]
I run the script above and insert 1024 rows in a batch, got the following error:
 12%|███▋                           | 1121281/9520308 [05:38<42:17, 3309.47it/s]
Traceback (most recent call last):
  File "/home/yzq/tmp/test_roaring/test.py", line 69, in <module>
    table_object.insert(to_insert)
  File "/home/yzq/miniconda3/envs/infinity/lib/python3.12/site-packages/infinity/remote_thrift/table.py", line 185, in insert
    raise InfinityException(res.error_code, res.error_msg)
infinity.common.InfinityException: (3013, 'INSERT: Target column count (13) and input value count mismatch (14)@src/planner/logical_planner.cpp:280')

data in the same insert batch should have the same insert columns

**Comment by miguelwon** [comment]
Yes, I realized that issue later on. Even so, the kernel still crashes when building the index afterward.

**Comment by yangzq50** [comment]
> Yes, I realized that issue later on. Even so, the kernel still crashes when building the index afterward.
Do you mean that you can insert all the 9M data, but cannot create index successfully?

**Comment by miguelwon** [comment]
Yes, that's the main problem. After inserting the 9M the index creating crashes. Probably related with memory, because I see the memory usage increase up to almost at 100% before the crash.

**Comment by yangzq50** [comment]
> Yes, I realized that issue later on. Even so, the kernel still crashes when building the index afterward.

You can try to first create the fulltext index and then insert data. I can Insert all the data by using less than 16G memory.

**Comment by yingfeng** [comment]
There's a memory issue for offline fulltext index building: first insert data, then create index.  The memory will consume more than expected which will lead to OOM. We'll fix it soon

**Comment by miguelwon** [comment]
@yangzq50 , I just tried with a 1M sample and if I first create the fulltext index and them populate, I see a relevant drop in my retrieval metrics. 
I tested also for Dense and Sparse, and I don't see the same type of impact.
