### ISSUE TITLE
[Bug]: show_index() not implemented in python module mode. 

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/infinity#1587]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.2.1

### Actual behavior and How to reproduce it

In Python module mode, it returns a localQueryResult instance after calling show_index(). 

### Expected behavior

Display the meta information about the index.

**Comment by JinHai-CN** [comment]
Remove this API from the document.

**Comment by JinHai-CN** [comment]
also remove API:
show_segments
show_segment
show_blocks
show_block
show_block_columns
optimize
