### ISSUE TITLE
[Question]: How should I use Chinese analyzer correctly?

### ISSUE THREAD

**Issue by xxzhang0927** [infiniflow/infinity#1609]
### Describe your problem

code:
res = table_instance.create_index(
        "my_index",
        [
            infinity.index.IndexInfo("body", infinity.index.IndexType.FullText, [infinity.index.InitParameter('analyzer', 'chinese')]),
        ],
        infinity.common.ConflictType.Error,
    )

error:
(<ErrorCode.INVALID_ANALYZER_NAME: 3079>, 'Invalid analyzer file path: /var/infinity/resource/jieba/dict/jieba.dict.utf8@src/storage/definition/index_full_text.cpp:63')

**Comment by JinHai-CN** [comment]
Check the examples: https://github.com/infiniflow/infinity/blob/main/example/fulltext_search_zh.py

> 
> Checkout https://github.com/infiniflow/resource.git under /var/infinity (defined by 'resource_dir' of config file). The jieba dict is
> /var/infinity/resource/jieba/dict/jieba.dict.utf8
