### ISSUE TITLE
`free(): invalid size` will occur after Insert reaches 20000 times

### ISSUE THREAD

**Issue by KKould** [infiniflow/infinity#161]
#### What happens?
![image](https://github.com/infiniflow/infinity/assets/91525956/204a3700-d1e0-4b30-9684-3b06acdbf151)

#### To Reproduce
```
    SizeT thread_num = 1;
    SizeT total_times = 2 * 10 * 1000;
```
![image](https://github.com/infiniflow/infinity/assets/91525956/61ad773e-79f2-4e7e-b696-085486c20009)

#### Environment (please complete the following information):
- infinity Version: [e.g. 0.0.1]
- infinity Client: [e.g. PG-Client]

#### Before Submitting

- [x] **Have you tried this on the latest `main` branch?**
- [x] **Give your commit id**: [29abad80b592537b7bb71af8c5d297216b0003cb](https://github.com/infiniflow/infinity/commit/29abad80b592537b7bb71af8c5d297216b0003cb)
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by yuzhichang** [comment]
Concurrent DELETE transactions cause some rows be deleted two times. 
It's necessary for `Txn::Commit()` to detect transaction conflict of this case.
