### ISSUE TITLE
[Feature Request]: Arithmetic operators like `abs` and `mod` are still not implemented in Python. 

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/infinity#1628]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Implement support for `abs` and `mod` in Python method `output()`.

**Comment by JinHai-CN** [comment]
Fixed by #1630

**Comment by writinwaters** [comment]
Please note abs() is implemented in output(), but not yet implemented in filter().

**Comment by yangzq50** [comment]
> Please note abs() is implemented in output(), but not yet implemented in filter().

Is this still a problem now?
