### ISSUE TITLE
[Bug]: Every time a full-text search is performed, the index must be recreated; otherwise, an empty result will be obtained

### ISSUE THREAD

**Issue by warran2** [infiniflow/infinity#1691]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.3.0-dev6

### Other environment information

```Markdown
操作系统：ubuntu 22
```

### Actual behavior and How to reproduce it

The first time search.py is executed, it can search for content normally; executing it again will return an empty result.

import_from_mysql.py

`
import infinity

from db import get_db_connection2
connection = get_db_connection2()
cursor = connection.cursor()

infinity_instance = infinity.connect("/var/infinity")
db_instance = infinity_instance.get_database("default_db")
db_instance.drop_table("zl_team", infinity.common.ConflictType.Ignore)
table_instance = db_instance.create_table("zl_team", {
        "id": {"type": "integer"},
        "name": {"type": "varchar"},
        "photo": {"type": "varchar"},
        "position": {"type": "varchar"},
        "location": {"type": "varchar"},
        "phone": {"type": "varchar"},
        "email": {"type": "varchar"},
        "business_field": {"type": "varchar"},
        "industry_field": {"type": "varchar"},
        "introduction": {"type": "varchar"},
        "key_achievements": {"type": "varchar"},
        "honors": {"type": "varchar"},
        "qualifications": {"type": "varchar"},
        "education_background": {"type": "varchar"},
        "work_experience": {"type": "varchar"},
        "working_languages": {"type": "varchar"},
        "social_positions": {"type": "varchar"},
        "publications": {"type": "varchar"}
    })

# 读取 zl_team 表中的数据
cursor.execute("SELECT * FROM zl_team")
rows = cursor.fetchall()
for row in rows:
    json_data = {
        "id": row[0] if row[0] is not None else "",
        "name": row[1] if row[1] is not None else "",
        "photo": row[2] if row[2] is not None else "",
        "position": row[3] if row[3] is not None else "",
        "location": row[4] if row[4] is not None else "",
        "phone": row[5] if row[5] is not None else "",
        "email": row[6] if row[6] is not None else "",
        "business_field": row[7] if row[7] is not None else "",
        "industry_field": row[8] if row[8] is not None else "",
        "introduction": row[9] if row[9] is not None else "",
        "key_achievements": row[10] if row[10] is not None else "",
        "honors": row[11] if row[11] is not None else "",
        "qualifications": row[12] if row[12] is not None else "",
        "education_background": row[13] if row[13] is not None else "",
        "work_experience": row[14] if row[14] is not None else "",
        "working_languages": row[15] if row[15] is not None else "",
        "social_positions": row[16] if row[16] is not None else "",
        "publications": row[17] if row[17] is not None else ""
    }
    table_instance.insert([json_data])
    # print("插入数据成功")
    # print(json_data)

res = table_instance.create_index(
        "introduction_index",
        infinity.index.IndexInfo("introduction", infinity.index.IndexType.FullText, {"ANALYZER": "chinese"}))

# infinity_instance.disconnect()

`

search.py

`import infinity

from db import get_db_connection2
connection = get_db_connection2()
cursor = connection.cursor()

infinity_instance = infinity.connect("/var/infinity")
db_instance = infinity_instance.get_database("default_db")
table_instance = db_instance.get_table("zl_team")

questions = [
        r"送达与取证", 
        r"商法",
    ]
for question in questions:
    qb_result = table_instance.output(["id", "name","location","introduction", "_score"]).match_text("introduction", question, 10).to_pl()
    print(f"question: {question}")
    print(qb_result)

res = table_instance.output(["id", "name", "introduction"]).to_pl()
print(res)

res = table_instance.show_index("introduction_index")
print(res)
# infinity_instance.disconnect()`

**Comment by yuzhichang** [comment]
Can you post your scripts as attachment?

**Comment by warran2** [comment]
Here are three Files

import_from_mysql2.py
Creating tables, importing data, creating indexes.

t2.py
Full-text search.

shell.txt
Execution process in the shell.

[
[infinity.zip](https://github.com/user-attachments/files/16686063/infinity.zip)
](url)

**Comment by yuzhichang** [comment]
I cannot reproduce this issue on Ubuntu 24.04. Here's my screenshot
![Screenshot_2024-08-21_14-25-53](https://github.com/user-attachments/assets/f2f01292-3b6c-456a-acf5-0e7b1b0bdf55)

Here's my procedure:
- Install conda
- Create Python 3.10 env and enter this env
- `pip install infinity-sdk==0.3.0-dev6`
- Create dir `/var/infinity` and ensure current user owns it
- Checkout Chinese dictionary under `/var/infinity/resources`
- Run modified `import_from_mysql2.py` once to create table, import data and create index.
- Run modified `t2.py` multiple times to search and show result. Ensure it succeed each time.

Here's my modified scripts:

[infinity.zip](https://github.com/user-attachments/files/16686980/infinity.zip)

**Comment by warran2** [comment]
In your screenshot

Pay attention to the red parts; the search results are different between the two searches.


![image](https://github.com/user-attachments/assets/3a458aad-6fdc-4dbb-8ccc-09a9ab43184e)

**Comment by warran2** [comment]
I don't understand what you mean.

I found when I split the fulltext_search_zh.py file from the example directory into two files:

One for creating the table and index
Another for querying

I encountered the same issue where the second search returns no data.

[infinity.zip](https://github.com/user-attachments/files/16689532/infinity.zip)

**Comment by yuzhichang** [comment]
I think I've found the root cause. The infinity embedded sdk `connect()` shall ensure MemIndexRecover actually done.

The fix will be available with next beta release, 0.3.0-dev7

**Comment by warran2** [comment]
ok,thanks for your reply
