### ISSUE TITLE
[Bug]: After inserting a record into the database, the database in docker cannot start.

### ISSUE THREAD

**Issue by joynn** [infiniflow/infinity#1702]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.3.0.dev5

### Actual behavior and How to reproduce it

Hello, I have a table which is created by using the following code.
```
rag_table_obj = db_obj.create_table(
            self.table_name,
            {
                "chunk_id": {"type": "varchar", "constraints": ["PRIMARY KEY"]},
                "kb_id": {"type": "varchar"},
                "user_no": {"type": "varchar"},
                "file_id": {"type": "varchar"},
                "file_name": {"type": "varchar"},
                "file_path": {"type": "varchar"},
                "timestamp": {"type": "varchar"},
                "content": {"type": "varchar"},
                "embedding": {"type": "vector, 768, float"},
            },
            ConflictType.Error
        )
```

After inserting a 768-dimensional vector data using QAnything from NetEase, infinity in docker cannot be started. The following error is reported in the background. What might be the reason?
```
libc++abi: terminating due to uncaught exception of type infinity::UnrecoverableException@infinity_exception: offset 238 is out of range 238@src/storage/column_vector/var_buffer.cpp:59
```

**Comment by JinHai-CN** [comment]
Can you reproduce the fault? If possible, would you please provide the code piece which lead to the fault?

BTW, the latest version is 0.3.0-dev6.

**Comment by JinHai-CN** [comment]
I write a script, but it can't reproduce the error. I attach it and you can try by yourself. 
[Uploading insert_many_columns_example.txt…]()

**Comment by joynn** [comment]
Thanks! I have deleted all the data files. Now it is a completely new environment and can be used temporarily. I don't know how to reproduce this problem. If I encounter it again next time, I will record it. Later, it will be upgraded to the latest version.
