### ISSUE TITLE
[Question]: how can infinity support full_text index for other language like chinese?

### ISSUE THREAD

**Issue by thunder95** [infiniflow/infinity#1782]
### Describe your problem

It performed very well when I use full text index on columns with english text. However, it returns always empty result when used on chinese text  column.

**Comment by yingfeng** [comment]
Hi, you could specify the parameter of  analyzer to "chinese", and put the analyzer dictionary to correct path.  The dictionary lies in another repo [resource](https://github.com/infiniflow/resource), and should be put according to suitable [configuration](https://github.com/infiniflow/infinity/blob/main/docs/references/configurations.md).

**Comment by thunder95** [comment]
@yingfeng many thx for your quick reply, it works well.
