### ISSUE TITLE
[Question]: Performance of using BGE-M3 in match_tensor fusion

### ISSUE THREAD

**Issue by PorYoung** [infiniflow/infinity#1810]
### Describe your problem

Are there any benchmarks for the Colbert Reranker search?

In my experiments, I employed a combination of `full-text`, `dense`, `sparse`, and `tensor` searches across over 4000 long documents (which would be split into a few segments). The vectors of segments were generated using BGE-M3 (featuring multilingual support) with a dimensionality of 1024.

Searches conducted solely with `dense` or `sparse` vectors completed in under **100 milliseconds**.

However, when combining `full-text` search (taking roughly 8 seconds) with Colbert `match_tensor` fusion (around **28 seconds**), the total duration for a single search extended to between 28 and 40 seconds.

**Device Information:**
CPU: Intel(R) Xeon(R) Gold 6248 (32 processors)
Memory: 64GB
Disk: 650GB (infinity store occupies 22GB)

**DDL Example:**
```py
create_table("table", {
  "text": {"type": "varchar"},
  "dense": {"type": "vector,1024,float"},
  "sparse": {"type": "sparse,250002,float,int"},
  "tensor": {"type": "tensor,1024,float"}
})
```

**DQL Example:**
```py
table.output(["*"])
  .match_dense("dense", dense, "float", "cosine", 100)
  .match_sparse("sparse", sparse, "ip", 100)
  .fusion(method="match_tensor", topn=10, fusion_params={"field": "tensor", "data_type": "float", "data": tensor})
  .to_pl()
```

> I am sorry, but due to some limitations, there is no more information I can provide.

**Comment by yingfeng** [comment]
Hi, it's not recommended to use common embedding for tensor based reranker such as BGE. Because it will output 1024 dim embeding for each token, this means that its space expands by 3 orders of magnitude compared to the original. If you have 1G text, it might got 1T tensor space. For reranker, it will load corresponding tensor data into memory. 

It's recommended to use jina-colbert-v2 because it will just output 128 dim for each token.  And if you use binary quantization, only 12 bytes are used for each token at a cost of a bit lower precision.


Regarding to your problem, you could guarantee the buffer manager to be large enough not to affect the performance.  By default it's:
```
buffer_manager_size      = "4GB"
```

Since tensor has occupied most space, make sure this data is large enough such as those tensor data could be loaded into memory.

**Comment by JinHai-CN** [comment]
> ### Describe your problem
> Are there any benchmarks for the Colbert Reranker search?
> 
> In my experiments, I employed a combination of `full-text`, `dense`, `sparse`, and `tensor` searches across over 4000 long documents (which would be split into a few segments). The vectors of segments were generated using BGE-M3 (featuring multilingual support) with a dimensionality of 1024.
> 
> Searches conducted solely with `dense` or `sparse` vectors completed in under **100 milliseconds**.
> 
> However, when combining `full-text` search (taking roughly 8 seconds) with Colbert `match_tensor` fusion (around **28 seconds**), the total duration for a single search extended to between 28 and 40 seconds.
> 
> **Device Information:** CPU: Intel(R) Xeon(R) Gold 6248 (32 processors) Memory: 64GB Disk: 650GB (infinity store occupies 22GB)
> 
> **DDL Example:**
> 
> ```python
> create_table("table", {
>   "text": {"type": "varchar"},
>   "dense": {"type": "vector,1024,float"},
>   "sparse": {"type": "sparse,250002,float,int"},
>   "tensor": {"type": "tensor,1024,float"}
> })
> ```
> 
> **DQL Example:**
> 
> ```python
> table.output(["*"])
>   .match_dense("dense", dense, "float", "cosine", 100)
>   .match_sparse("sparse", sparse, "ip", 100)
>   .fusion(method="match_tensor", topn=10, fusion_params={"field": "tensor", "data_type": "float", "data": tensor})
>   .to_pl()
> ```
> 
> > I am sorry, but due to some limitations, there is no more information I can provide.

Use config file as below: 
`
buffer_manager_size      = "32GB"
`

**Comment by PorYoung** [comment]
@JinHai-CN @yuzhichang Much appreciation! My original `buffer_manager_size` was 16GB, and increasing it to 32GB solved my problem. Thanks for your suggestion. I’ll try Jina-ColBERT-v2.

How should I adjust the buffer size to achieve the best performance? Does this parameter control the maximum cache size that Infinity can hold in memory? And is a larger size preferable?

**Comment by JinHai-CN** [comment]
Yes, this is the capacity of the buffer used to cache the data/index.

**Comment by PorYoung** [comment]
Once I obtain further information, I will provide an update here.
