### ISSUE TITLE
[BUG]: Incorrect PSQL DateStyle: IOS, DMY

### ISSUE THREAD

**Issue by PorYoung** [infiniflow/infinity#1895]
https://github.com/infiniflow/infinity/blob/e761e5cb41d21514a41096818002c971049a513a/src/network/connection.cpp#L104

Error Message From JDBC Driver:

```
The server's DateStyle parameter was changed to IOS, DMY. The JDBC driver requires DateStyle to begin with ISO for correct operation.
```

It seems to be `ISO, DMY`?

**Comment by JinHai-CN** [comment]
Infinity does use pg wire protocol. But Infinity doesn't support PG SQL at all. The interface of SQL can only be used for debug/testing.

If you want to use access Infinity, you can try the HTTP or python API.
