### ISSUE TITLE
[Bug]: infinity.connect not accepting valid local directory path strings

### ISSUE THREAD

**Issue by davidtbo** [infiniflow/infinity#1898]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

0.3.0, 0.4.0.dev1

### Other environment information

```Markdown
Ubuntu 22.04, 
Python 3.10.12
```

### Actual behavior and How to reproduce it

```
import infinity
infinity_object = infinity.connect("/home/dave/project/data")
```
Results in error:

`infinity.common.InfinityException: (<ErrorCode.INVALID_SERVER_ADDRESS: 7016>, 'Unknown uri: /home/dave/project/data')`

Directory exists and Infinity created it, as well as a log directory therein, with logs in it. I'm not sure why it says it can't connect after it already created two directories and wrote in one of them

### Expected behavior

successful connection to a local database path as documented

**Comment by JinHai-CN** [comment]
In 0.4.0, there are two infinity python module: infinity-sdk and infinity-embedded-sdk. You can try to use infinity-embedded-sdk to open local data directory.

**Comment by JinHai-CN** [comment]
@writinwaters 0.4.0 Documents need to update according to the change.
