### ISSUE TITLE
[Question]: Build Procedure on RHEL/Rocky 8 Without Docker + C/C++ API Access

### ISSUE THREAD

**Issue by mesibo** [infiniflow/infinity#1912]
1. We want to build infinity on RHEL/Rocky 8 without using Docker. Could you please provide a build procedure or any relevant documentation that can help us with this setup?

2. Additionally, although the project is developed in C/C++, there is only documentation for the Python API. We plan to integrate mesibo's real-time APIs into our workflow and would like to access the C/C++ API instead of the Python one. Could you guide us on where to find the C/C++ API documentation, and how to get started with it?

Thanks!

**Comment by JinHai-CN** [comment]
1. Check the centos7 dockerfile: [dockerfile](https://github.com/infiniflow/infinity/blob/main/scripts/Dockerfile_infinity_builder_centos7)

Please also refer to the [build_from_source](https://infiniflow.org/docs/build_from_source). Althrough the document is for Ubuntu, it also tell us which libraries are necessary for Infinity.

2. Two ways to access Infinity in C/C++:
- HTTP API: https://infiniflow.org/docs/http_api_reference
- Thrift client: I tried to write a test C++ client here: https://github.com/infiniflow/infinity/tree/main/client/cpp, but considering most users of Infinity using Python / JS. I didn't continue maintaining it. You can follow it and write your thrift client.
