### ISSUE TITLE
[Bug]: When executing the "copy" command through PgSQL and the directory does not exist, it can cause the Infinispan server to crash.

### ISSUE THREAD

**Issue by GuangchaoDeng** [infiniflow/infinity#1956]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.4.0-dev2

### Actual behavior and How to reproduce it

When executing the "copy" command through PgSQL and the directory does not exist, it can cause the Infinispan server to crash.

**Comment by JinHai-CN** [comment]
Fixed by #1951
