### ISSUE TITLE
[Bug]: The Infinity server's memory usage is continuously increasing until it completely consumes system memory

### ISSUE THREAD

**Issue by GuangchaoDeng** [infiniflow/infinity#1957]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.4.0-dev2

### Actual behavior and How to reproduce it

1. Multiple databases exist
2. Table data exists in each database
3. Start infinity

**Comment by JinHai-CN** [comment]
I suppose #1949 fixed part of this issue.

**Comment by GuangchaoDeng** [comment]
resolved
