### ISSUE TITLE
[Bug]: Can't insert sparse in format like `{"10":1.1, "20":2.2, "30": 3.3}`

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/infinity#1992]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.4.0.dev2, Python SDK

### Actual behavior and How to reproduce it

Currently, only `SparseVector([10, 20, 30], [1.1, 2.2, 3.3])` is supported.

**Comment by small-turtle-1** [comment]
Append in dict format is accepted.
set default value in such type cause error.
```sql
table_instance.add_columns({"column_name1": {"type": "sparse,128,float,int", "default": {{"10":1.1, "20":2.2, "30": 3.3}}}})
```

**Comment by yangzq50** [comment]
The following code works
```python3
table_instance.add_columns({"column_name1": {"type": "sparse,128,float,int", "default": {"10":1.1, "20":2.2, "30": 3.3}}})
```
