### ISSUE TITLE
[Bug]: Misleading Python SDK readme 

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/infinity#2065]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.4.0

### Actual behavior and How to reproduce it

The imported module is infinity-embedded.

### Expected behavior

The module to import ought to be Infinity.

**Comment by writinwaters** [comment]
https://pypi.org/project/infinity-embedded-sdk/

**Comment by JinHai-CN** [comment]
infinity-sdk and infinity-embedded sdk should have different README.
