### ISSUE TITLE
[Bug]: Restart test fail

### ISSUE THREAD

**Issue by Ami11111** [infiniflow/infinity#2066]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.4.0

### Actual behavior and How to reproduce it

https://github.com/infiniflow/infinity/actions/runs/11400249704/job/31720694937?pr=2064

**Comment by JinHai-CN** [comment]
https://github.com/infiniflow/infinity/actions/runs/11382091977/job/31664876798

**Comment by small-turtle-1** [comment]
Test case bug.
