### ISSUE TITLE
[Bug]: Escape characters for full text search syntax

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/infinity#2145]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

d7d042b62a076b03e3f262ae43227f1c8da57a49

### Actual behavior and How to reproduce it

Given query
```
电影《厕所:一个爱的故事》改编自什么故事？
```

`厕所` is interpreted as column name due to the colon in the query, which should be escaped.  
Similar builtin characters should also be escaped for robust full text search.

**Comment by yangzq50** [comment]
You can add `{"operator": "or"}` in fulltext query option, for example:
https://github.com/infiniflow/infinity/blob/000fcb77d34878019a97a97a47159293fe3e012c/python/test_pysdk/test_knn.py#L707
