### ISSUE TITLE
[Bug]:  An error occurred during query parsing.

### ISSUE THREAD

**Issue by GuangchaoDeng** [infiniflow/infinity#2148]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

0.4.0

### Actual behavior and How to reproduce it

**执行查询语句如下：**
电影《厕所: 一个爱的故事》改编自什么故事？
**错误如下：**
infinity.comon, infinityException: (3024,"column: 厕所 doesn't existasrc/storape/meta/entry/table entry.cp: 1212asrc/scheduler/fragent context.cp:1417")

**Comment by yingfeng** [comment]
duplicate with #2145
