### ISSUE TITLE
[Question]: Question on GUI deployment

### ISSUE THREAD

**Issue by Yangjinsen8-1** [infiniflow/infinity#2182]
### Describe your problem

尊敬的开发者，你们好。
近日在部署gui项目时，通过 next.js相关的配置 output:"standalone"生成的部署文件包。在我将其放于我的服务器上，通过在standalone文件夹下执行node server.js命令时，出现报错信息'Cannot find module 'styled-jsx/package.json'，文件路径显示为'standalone/node_modules/next/dist/server/require-hook.js'。请问我该如何解决呢？

**Comment by cike8899** [comment]
1. pnpm run build
2. pnpm run start

**Comment by Yangjinsen8-1** [comment]
你好，首先非常感谢楼上的回复。其次直接build生成的文件放于服务器运行需要上传相应的node依赖，以及package.json文件，然后在服务器执行start命令。目前需要生成类似于部署vue或react的文件包，不需要过多的node依赖包，以及package.json文件

**Comment by cike8899** [comment]
I set the output to "standalone" and the problem you mentioned did not occur. I copied the built standalone folder to the server and it ran successfully, but I had to copy .next/static to standalone/public/_next/static, like this

![image](https://github.com/user-attachments/assets/120854aa-684c-4e1b-be62-cf9e0946111c)
