### ISSUE TITLE
[Bug]: In the  RAG indexing, the query returns an error :"3013, 'Empty query text'

### ISSUE THREAD

**Issue by GuangchaoDeng** [infiniflow/infinity#2193]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

0.5.0

### Actual behavior and How to reproduce it

查询语句：
what is the caus of the victim 's condit ? "what is" "is the" "the caus" "caus of" "of the" "the victim" "victim 's" "'s condit" "condit ?"
索引类型：
rag全文索引

**Comment by yingfeng** [comment]
`'`, `:` should be escaped before sending to `infinity`
` what is the caus of the victim \'s condit ? "what is" "is the" "the caus" "caus of" "of the" "the victim" "victim \'s" "\'s condit" "condit ?"`
