### ISSUE TITLE
[Bug]: The database crashes when displaying table information in standalone mode.

### ISSUE THREAD

**Issue by wxzkenny** [infiniflow/infinity#2206]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

bcde5251945c88670a5f09c98c1c10d11e05affc

### Other environment information

```Markdown
Hardware: X86_64
OS type: 
 $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
 $ uname -a
Core Info: Linux ibp 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

infinity version:
Release: 0.5.0 build on 2024-11-05 13:21.45 with RelWithDebInfo mode from branch: main, commit-id: bcde5251945c88670a5f09c98c1c10d11e05affc
```

### Actual behavior and How to reproduce it

Configuration file of the follower instance：
[follower.toml](https://github.com/user-attachments/files/17672083/follower.toml.txt)

Start the follower node via following command:
``` SHELL
infinity -f  follower.toml
```

The follower node executes the following command:
$  psql -h 0.0.0.0 -p 5001
``` SQL
ADMIN SHOW NODE;
ADMIN SET STANDALONE;
ADMIN SHOW NODE;

SHOW TABLES;
CREATE TABLE follower_table_standalone_mode (id INT, name VARCHAR);
SHOW TABLES;
CREATE TABLE follower_empty_table_standalone_mode (id INT, name VARCHAR);
SHOW TABLES;
```

Screenshot of the error：
![image](https://github.com/user-attachments/assets/725ed560-7608-40ce-b3ab-890a39ed35d8)

Log of the database at the time of error：
![image](https://github.com/user-attachments/assets/cca05275-b005-403c-94b9-5de165d8ac4f)

### Expected behavior

Ideally, if supported, it should execute correctly; if not supported, it should return an error rather than causing a database crash.

**Comment by JinHai-CN** [comment]
Tested successfully in the version of 0.5.0-dev2.
