### ISSUE TITLE
[Question]: How soon can the next version be released? I see a lot of bugs have been fixed recently

### ISSUE THREAD

**Issue by 1006076811** [infiniflow/infinity#2342]
### Describe your problem

How soon can the next version be released? I see a lot of bugs have been fixed recently

**Comment by JinHai-CN** [comment]
Infinity will be released in this week, if all serious bugs are fixed.

**Comment by JinHai-CN** [comment]
Postponed to next week.

**Comment by JinHai-CN** [comment]
Released, https://github.com/infiniflow/infinity/releases/tag/v0.5.0
