### ISSUE TITLE
[Bug]: Not getting any ouput in v0.5.0-dev7 but previous on version v0.4.0

### ISSUE THREAD

**Issue by zokkomon** [infiniflow/infinity#2381]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.5.0-dev7 

### Other environment information

```Markdown
Hardware parameters:amd ryzen 5
OS type: ubuntu 22.4
```

### Actual behavior and How to reproduce it

[warn] Infinity::LocalInit cannot find config: conf/pytest_embedded_infinity_conf.toml
[info] No config file is given, use default configs.
No config file is given, use default configs.
Infinity system configs: 
 - version: 0.5.0
 - timezone: UTC8
 - cpu_limit: 8
 - server mode: standalone
 - server address: 0.0.0.0
 - peer server ip: 0.0.0.0
 - peer server port: 23850
 - postgres port: 5432
 - http port: 23820
 - rpc client port: 23817
 - connection pool size: 256
 - peer server connection pool size: 256
 - log_filename: infinity.log
 - log_dir: /var/infinity/log
 - log_file_path: /var/infinity/log/infinity.log
 - log_to_stdout: false
 - log_file_max_size: 1.00GB
 - log_file_rotate_count: 8
 - log_level: Info
 - persistence_dir: /var/infinity/persistence
 - persistence_file_size: 134217728
 - data_dir: /var/infinity/data
 - cleanup_interval: 10s
 - compact_interval: 10s
 - optimize_index_interval: 10s
 - memindex_capacity: 1048576
 - dense_index_building_worker: 4
 - sparse_index_building_worker: 4
 - fulltext_index_building_worker: 4
 - storage_type: local
 - buffer_manager_size: 8.00GB
 - temp_dir: /var/infinity/tmp
 - memindex_memory_quota: 4.00GB
 - wal_dir: /var/infinity/wal
 - buffer_manager_size: 1.00GB
 - full_checkpoint_interval: 30s
 - delta_checkpoint_interval: 5s
 - delta_checkpoint_threshold: 64.00MB
 - flush_method_at_commit: FlushAtOnce
 - resource_dir: /var/infinity/resource

### Expected behavior

[info] No config file is given, use default configs.
No config file is given, use default configs.
2024-12-16 23:38:01,971 - INFO - Document already exists in the database: machine learning
[info] No config file is given, use default configs.
No config file is given, use default configs.
shape: (1, 5)
┌─────────────────────────────────┬──────────────────┬─────────────────────────────────┬───────────┬──────────┐
│ id                              ┆ text             ┆ vec                             ┆ sparse    ┆ SCORE    │
│ ---                             ┆ ---              ┆ ---                             ┆ ---       ┆ ---      │
│ str                             ┆ str              ┆ list[f64]                       ┆ struct[1] ┆ f32      │
╞═════════════════════════════════╪══════════════════╪═════════════════════════════════╪═══════════╪══════════╡
│ d31623b04635761196d9a198a473bf… ┆ machine learning ┆ [-0.038245, 0.006042, … 0.0245… ┆ {1.0}     ┆ 2.269412 │
└─────────────────────────────────┴──────────────────┴─────────────────────────────────┴───────────┴──────────┘

### Additional information

and running flask causing Segmentation core dumped

**Comment by JinHai-CN** [comment]
The transaction log format of 0.5.0 is not compatible with 0.4.0, and errors may occur when replaying the log. If the data was previously stored in 0.4.0, you can use the export command to export the data as a JSON or Parquet file, and then import it in 0.5.0.
