### ISSUE TITLE
[Bug]: libc++abi: terminating due to uncaught exception of type infinity::UnrecoverableException@infinity_exception: BufferManager::Allocate: 

### ISSUE THREAD

**Issue by wz96cj** [infiniflow/infinity#2403]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.5.0

### Actual behavior and How to reproduce it

![PixPin_2024-12-24_13-51-16](https://github.com/user-attachments/assets/b49cbcb2-ed1c-406d-a13c-8eeb9e961c6c)

**Comment by JinHai-CN** [comment]
Can you reproduce the fault? Would you please describe the steps?

**Comment by wz96cj** [comment]
> Can you reproduce the fault? Would you please describe the steps?

 when restarting Docker today; it seems like it’s a problem with duplicate data.

**Comment by JinHai-CN** [comment]
Yes, looks like some objects in database are already allocated. Can you reproduce the fault again, or the issue is already fixed after restart the container?

**Comment by wz96cj** [comment]
> Yes, looks like some objects in database are already allocated. Can you reproduce the fault again, or the issue is already fixed after restart the container?是的，看起来数据库中的一些对象已经分配了。能否再次重现该故障，或者重启容器后问题已经解决？

It is difficult to reproduce this problem. For now, I can only delete the  infinity_data folder to resolve the issue.

**Comment by JinHai-CN** [comment]
If this issue is reproduced again, please let us know.
