### ISSUE TITLE
table star expressions

### ISSUE THREAD

**Issue by loloxwg** [infiniflow/infinity#33]
#### What happens?
SELECT test_table_star.* FROM test;
<img width="941" alt="CleanShot 2023-09-19 at 11 16 13@2x" src="https://github.com/infiniflow/infinity/assets/56066360/b2f17df6-0fef-4056-8ccd-8a20097a7273">

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

1. CREATE TABLE test_table_star(a INTEGER, b INTEGER, c INTEGER);
2. COPY test_table_star FROM 'test/data/csv/integer.csv' WITH ( DELIMITER ',' );
3. SELECT test_table_star.* FROM test;

#### Environment (please complete the following information):
- OS: ubuntu22.04
- infinity Version: [e.g. 0.0.1]
- infinity Client: sqllogictest-rs

#### Before Submitting

- [x] **Have you tried this on the latest `main` branch?**
- [ ] **Give your commit id** eaf2c888faf06dee8db7e0e1f60dba22dc01e91c
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by JinHai-CN** [comment]
This bug isn't valid any more.
