### ISSUE TITLE
Predicate condition does not work

### ISSUE THREAD

**Issue by loloxwg** [infiniflow/infinity#35]
#### What happens?
SELECT a , b FROM test_table_star where a =4
<img width="415" alt="CleanShot 2023-09-19 at 11 48 21@2x" src="https://github.com/infiniflow/infinity/assets/56066360/10dbea83-c3c5-43d9-ba66-7dac0eb00974">

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
<img width="86" alt="CleanShot 2023-09-19 at 11 49 20@2x" src="https://github.com/infiniflow/infinity/assets/56066360/e4f0c4e6-c0b0-4dc3-bd8d-2c7381615269">

SELECT a , b FROM test_table_star where a =4;

#### Environment (please complete the following information):
- OS: [e.g. ubuntu22.04]
- infinity Version: [e.g. 0.0.1]
- infinity Client: [PG-Client]

#### Before Submitting

- [x] **Have you tried this on the latest `main` branch?**
- [ ] **Give your commit id** eaf2c888faf06dee8db7e0e1f60dba22dc01e91c
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by JinHai-CN** [comment]
Fixed
