### ISSUE TITLE
[Feature Request]: Secondary index

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/infinity#360]
Secondary index is used for numeric filtering. It is composed of two parts:
1. The data of each numeric column is stored in an inverted sorted form, with a compressed format.
2. Another in-memory part of index data which is based on [pgm](https://github.com/infiniflow/infinity/tree/main/src/storage/invertedindex/pgm), it could provide very fast approximate range query with bounded error, which has already been added into the repository.
 
The mechanism of range filtering of secondary index is as follows:
1. Query the pgm index to get the bounded range.
2. Scan the raw index data according to bounded range to get the RowIDs of the query filter.

**Comment by yangzq50** [comment]
My comments for the implementation:
1.  When building secondary index for a numeric column in the table, we can build one secondary index structure for each segment of the table.

2. Every secondary index structure should contain 3 parts:
2.1. pgm: a data structure which provides approximate range
2.2. vector_value: sorted array of all the values of the chosen column in the segment (necessary for getting exact range)
2.3. vector_offset: array of segment offsets for each value in vector_value (necessary for getting filtering results)

3. vector_value and vector_offset can be split into parts with max size 8192

4. Steps for range search of one column with secondary index:
4.1. Get an approximate range from pgm
4.2. Get the exact range by binary search in vector_value
4.3. Generate a bitmask (when the size of the exact range is too big) or a vector of chosen offsets

**Comment by yingfeng** [comment]
4.2 is not necessary because pgm has already told the approximate range, as a result 4.2 is acturally a linear scan

>     4. Steps for range search of one column with secondary index:
>        4.1. Get an approximate range from pgm
>        4.2. Get the exact range by binary search in vector_value
>        4.3. Generate a bitmask (when the size of the exact range is too big) or a vector of chosen offsets

**Comment by yangzq50** [comment]
subtask #476 and subtask #477 are deferred to #637
