### ISSUE TITLE
[Bug]: The doc, build from source, has multiple errors and issues. Follow the doc and go through it. I can not build

### ISSUE THREAD

**Issue by bonito-skipjack** [infiniflow/infinity#376]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

47a1e7e316adc56c314225fcacd1003cf4a8eeb6

### Other environment information

```Markdown
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

### Actual behavior

https://github.com/infiniflow/infinity/blob/main/docs/build_from_source.md
<img width="745" alt="image" src="https://github.com/infiniflow/infinity/assets/114712925/abf3952d-492f-4d03-9bc2-d39c088978c6">
Once I have git, I can use git clone, so I don't need to install git again.
<img width="967" alt="image" src="https://github.com/infiniflow/infinity/assets/114712925/a1348741-f72a-4879-871a-209f79b053e6">
sudo only works for echo
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/llvm-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] https://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main" | sudo tee /etc/apt/sources.list.d/llvm17.list
sudo apt update
sudo apt install clang-17 clang-tools-17
![image](https://github.com/infiniflow/infinity/assets/114712925/7602e1a3-7447-4b83-b386-62842b516bb3)
Installing clang-17 but using clang-18
There are dependencies on lz4 and boost, but they are not installed.

### Steps to reproduce

```Markdown
Build from source on Ubuntu 22.04
```

**Comment by writinwaters** [comment]
Thanks @bonito-skipjack for the detailed instructions. We'll fix these shortly after. Haste makes waste... 

Cheers
Writinwaters

**Comment by yangzq50** [comment]
lz4 and boost should be installed by the following command in the doc
`apt install g++-13 clang-17 clang-tools-17 flex libboost1.81-dev liblz4-dev libevent-dev liburing-dev libthrift-dev`
Why they are not installed?

**Comment by JinHai-CN** [comment]
If there are more problems, we will reopen this issue.
