### ISSUE TITLE
[Bug]: incorrect class forward declarations in module interface

### ISSUE THREAD

**Issue by AndreyG** [infiniflow/infinity#405]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

d022098a06a2ce4047f6adc0b72600d15c6bc759

### Actual behavior

There are a lot of forward declarations of classes which are actually defined in another modules, this is incorrect.
For instance, here https://github.com/infiniflow/infinity/blob/d022098a06a2ce4047f6adc0b72600d15c6bc759/src/planner/node/logical_fusion.cppm#L30 class `TableCollectionEntry` is declared in the module `logical_fusion`, and it contradicts to the fact that it's actually defined in the module `table_collection_entry` https://github.com/infiniflow/infinity/blob/cd7039715b1fefc635500aacd2535a3796d18b14/src/storage/meta/entry/table_collection_entry.cppm#L44
This is very bad situation (IFNDR): https://eel.is/c++draft/basic.link#10.

### Steps to reproduce

```Markdown
...
```

**Comment by yingfeng** [comment]
Thank you, there does exist many forward declarations which could be replaced by importing modules directly.
