### ISSUE TITLE
Minmax of column data.

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#448]
Infinity need the min max column value information of each column in the segment/block. With this information and condition expression, infinity may filter out some data segments/blocks before table scan.

Currently, I suppose these information will co-located with the information of segment / block which is in catalog.

**Comment by Kelvinyu1117** [comment]
I would like to have a try, I guess I should start with `segment_entry.cppm`?

**Comment by JinHai-CN** [comment]
Besides segment_entry，block_entry also impacted.

On this feature, you might need to consider following things:
1. Will insert and delete data update minmax value?
2. Import new data might also generate the minmax of segment and block.
3. Minmax also need to be serialized as other attribute of the segment/block entey.
4. How to represent the minmax of different column data type? Value or other way?

So, we will appreciated it if you can give an implemention proposal here, before you write the code.

**Comment by JinHai-CN** [comment]
Nice
