### ISSUE TITLE
This line does nothing

### ISSUE THREAD

**Issue by billhoffman** [infiniflow/infinity#464]
https://github.com/infiniflow/infinity/blob/e3ee4943c902b9f622885e6fb3169a0a2f82b5e5/CMakeLists.txt#L5

You can not set the generator in CMake. It is a read only variable. The it is specified by the -G option to CMake and once picked can not be changed. This could be changed to a fatal error if the generator is not ninja.

**Comment by yuzhichang** [comment]
Good catch. This will be fixed in PR #465.
