### ISSUE TITLE
[Bug]: Give none string type database name to Python SDK will introduce SDK raise exception

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#473]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

171b3de65f1f67b5f3e5eb00fcfc35074e4d9774

### Actual behavior

use following type as the database name to call infinity_obj.create_database will introduce py raise exception.

[],
(),
{},
1,
1.1,

### Steps to reproduce

```Markdown
Just use those as the db_name to create database
```

**Comment by chrysanthemum-boy** [comment]
It looks fixed.
