### ISSUE TITLE
[Bug]: Create table with invalid column name, no error is raised.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#488]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

f9da7b7

### Actual behavior

Call create table with invalid name by SDK, no error is raised.

invalid name including:
- empty name
- invalid character violate the rules
- too long name

### Steps to reproduce

```Markdown
`Just call the create_table API, get_table API. Just the name is invalid.`
```

**Comment by JinHai-CN** [comment]
Please provide the detailed test cases, what kind of table name doesn't raise exception.

**Comment by chrysanthemum-boy** [comment]
Call create_table with invalid  `column name`  by SDK, no error is raised.
invalid name including: 
 - list, such as`[]`,
  - tuple, such as`()`,
  - dict,such as `{}`,
  - int, such as `1`,
  - float, such as `1.1`,

**Comment by chrysanthemum-boy** [comment]
The bug has been fixed.
