### ISSUE TITLE
[Feature Request]: Show Variable

### ISSUE THREAD

**Issue by loloxwg** [infiniflow/infinity#495]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
show system parameters for pysdk
```

### Describe the feature you'd like

show system parameters for pysdk

**Comment by JinHai-CN** [comment]
SQL syntax: SHOW VAR var_name

Currently, we already have following system variables:
query_count
session_count
buffer_pool_usage
version
query_memory_limit
query_cpu_limit
log_level
schedule_policy
listen_address
sql_port
sdk_port
http_api_port
data_url
time_zone

For detailed information, you may check src/main/config.cpp
