### ISSUE TITLE
[Bug]: Continuously droping 1000 tables, the service terminates

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#504]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

479f61e

### Actual behavior

On CI system when droping 1000 tables, the service terminates.

### Steps to reproduce

```Markdown
Just use for loop to drop 1000 tables.
```

**Comment by JinHai-CN** [comment]
Can't reproduce any more.

**Comment by chrysanthemum-boy** [comment]
It looks fixed.
