### ISSUE TITLE
[Bug]: When create a database with an invalid name, an error occurs when disconnect.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#506]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

479f61e

### Actual behavior

When using such as `[]` or `{}` or `()` or `1` or `1.1` as the database name and when diconnect the infinity object the error occurs.

### Steps to reproduce

```Markdown
Just call create_database with invalid name, and then disconnect the error occurs.
```

**Comment by JinHai-CN** [comment]
If the bug is fixed, please close it.
