### ISSUE TITLE
[Bug]: Delete in empty table, the service throw a critical and shutdown.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#511]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

479f61e

### Actual behavior

Delete in empty table, the service throw a critical and shutdown.
![image](https://github.com/infiniflow/infinity/assets/69421435/f45ce0e1-d908-4e3f-b647-8c576bbc16b2)

### Steps to reproduce

```Markdown
Just create an empty table, and call table_obj.delete("c1 = 1"), the service shutdown.
The test function is in /python/test/test_delete.py which named test_delete_empty_table.
```

**Comment by JinHai-CN** [comment]
Looks the bug is already fixed.
