### ISSUE TITLE
[Bug]: When delete the table with specified condition, occurs some errors.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#519]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

40bf795

### Actual behavior

create a table with various column types, when delete table with specified condition the column types `float` ,`varchar` ,`bool` and `vector` types cannot operate normally.
the code is in `test_delete.py/test_delete_table_all_row_met_the_condition`
- use bool types, when delete table with specified condition
![image](https://github.com/infiniflow/infinity/assets/69421435/3b540583-0f10-4652-bede-ded5e8598369)
- use `vector` types, server shutdown
![image](https://github.com/infiniflow/infinity/assets/69421435/ff51f3ea-e9e5-4a40-8e8f-3e1188e838cf)

### Steps to reproduce

```Markdown
Just check the function test code in test_delete.py/test_delete_table_all_row_met_the_condition.
The test types check in the common_values.py types_array.
```

**Comment by JinHai-CN** [comment]
Fixed
