### ISSUE TITLE
[Bug]: When update the table with specified condition, some errors occur.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#534]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

4b0fa54

### Actual behavior

Create a table with column type `varchar`, `bool`, and when update the table with specific condition errors occur.
- `varchar` error
![image](https://github.com/infiniflow/infinity/assets/69421435/9519d623-3ecc-45fd-ab34-de2b0014fd23)
- `bool` error
![image](https://github.com/infiniflow/infinity/assets/69421435/507e57f0-1d07-4f3d-b6a0-28dc7985a62e)

### Steps to reproduce

```Markdown
Check the file in /python/test/test_update.py 
def test_update_all_row_is_met_the_condition
def test_update_no_row_is_met_the_condition

the test examples are in /python/test/common_values.py
```

**Comment by JinHai-CN** [comment]
Fixed.

**Comment by chrysanthemum-boy** [comment]
It looks fixed.
