### ISSUE TITLE
[Bug]: When insert/delete an int128 column type data some errors occur.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#581]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1ca85c2

### Actual behavior

Errors occur when inserting or deleting int128 type data.
![image](https://github.com/infiniflow/infinity/assets/69421435/8b2b4e11-724c-47b9-a37a-1c181cdaa554)
Error after starting infinity again.
![image](https://github.com/infiniflow/infinity/assets/69421435/51a3af59-abad-4fcf-86d9-aa08d0bc6436)

### Steps to reproduce

```Markdown
Function test code is in python/test/test_delete.py `test_delete_table_all_row_met_the_condition`.

Test examples are in python/test/common_values.py
```

**Comment by JinHai-CN** [comment]
int128 type isn't supported now.

**Comment by chrysanthemum-boy** [comment]
OK, I will submit it as a feature request.
