### ISSUE TITLE
[Bug]: Create a table with float column type, and when delete the table, the service aborted.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#588]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1ca85c2e

### Actual behavior

Create table with `float` column type, and delete table use`table_obj.delete("c1 = 1")` some errors occur.
`[critical] Column vectors in same data block have different size.@src/storage/data_block.cpp:215
terminate called after throwing an instance of 'infinity::UnrecoverableException@infinity_exception'
  what():  Column vectors in same data block have different size.@src/storage/data_block.cpp:215
Aborted (core dumped)
`

### Steps to reproduce

```Markdown
Function test code can be found in python/test/test_delete.py `test_various_expression_in_where_clause`.

Test examples are in python/test/common_values.py
```

**Comment by Ognimalf** [comment]
Fixed

**Comment by chrysanthemum-boy** [comment]
It looks fixed.
