### ISSUE TITLE
[Feature Request]: Error handle on thrift server

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#626]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
#605
```

### Describe the feature you'd like

Currently, Infinity already has error code when error happens. But in thrift protocol, no error field in the response message. And error handle in thrift server part isn't complete. Such as in #605, if there is no such table instance, no any error handling. Similar cases can be found in other different cases.

**Comment by JinHai-CN** [comment]
Resolved and ready for test.

**Comment by chrysanthemum-boy** [comment]
It seems like there are no problems.
