### ISSUE TITLE
[Bug]: Creating a table with vector column type, when creating index with Hnsw type, the service shutdown.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#656]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

d8f8d37d

### Actual behavior

When creating a table with column type `"vector, 3, float"`, and creating index with `index_type=index.IndexType.Hnsw`.
```
[critical] Invalid index parameter@src/storage/definition/index_hnsw.cpp:74
Unrecoverable error issued, stop the serverShutdown infinity server ...
Shutdown storage ...
```

### Steps to reproduce

```Markdown
Function test code can be found in python/test/test_index.py `test_create_index_on_different_type_of_column`
```

**Comment by Ognimalf** [comment]
Fixed.

**Comment by chrysanthemum-boy** [comment]
It looks fixed.
