### ISSUE TITLE
[Feature Request]: Update the output filter function

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#682]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Add more specific filter to output function.

**Comment by Ognimalf** [comment]
#900 modifies `query_builder` in python sdk to support parsing expression fields for output.

**Comment by chrysanthemum-boy** [comment]
OK, it looks good.
