### ISSUE TITLE
[Bug]: Inserting data with unmatched column names, error occurs.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#688]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

6f8b3cb2

### Actual behavior

Inserting data with unmatched column names, error occurs.
```
 [critical] No column name: c2@src/storage/meta/entry/table_entry.cpp:615
Unrecoverable error issued, stop the serverShutdown infinity server ...
Shutdown storage ...
```

### Steps to reproduce

```Markdown
Function test code can be found in python/test/test_insert.py`test_insert_no_match_column`
```

**Comment by JinHai-CN** [comment]
Fixed by #696 and #699
