### ISSUE TITLE
[Feature Request]: Add python SDK option function.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#732]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Add delimiter choice option `","` `";"` `" "` `"    "` or other symbol.
- Add csv header option `True` or `False`.
- Add create table option function.
- Add update table option function.

**Comment by lxr599** [comment]
- If the coming file is a `.csv`, `options` can be a dictionary consisting of "delimiter" and "hasHeader" fields which need to be specified by the user. 
- For `create_table`, `options` can be a `bool` value. `true` means `create table ... if not exists`, `false` means `create table ...`. Default value is `false`.

**Comment by JinHai-CN** [comment]
Fixed by #824

**Comment by chrysanthemum-boy** [comment]
It looks fixed.
