### ISSUE TITLE
[Bug]: sqllogictest.py bug

### ISSUE THREAD

**Issue by small-turtle-1** [infiniflow/infinity#741]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

f3f9a24

### Actual behavior

run `python ./tools/sqllogictest.py` twice and has a unexpected answer.
"skip copy" cause the bug.

### Steps to reproduce

```Markdown
python ./tools/sqllogictest.py
python ./tools/sqllogictest.py
```

**Comment by chrysanthemum-boy** [comment]
Fixed.
