### ISSUE TITLE
[Bug]: Not support to convert Embedding to Embedding.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#760]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ee6e4533

### Actual behavior

`Exception: ERROR:3049, Not support to convert Embedding to Embedding@src/expression/cast_expression.cpp:39`

### Steps to reproduce

```Markdown
When update table with embedding data, an error occurs.
```

**Comment by JinHai-CN** [comment]
Fixed
