### ISSUE TITLE
[Bug]: Ｗhen create table with invalid option, can't disconnect infinity service.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#766]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ee6e4533

### Actual behavior

Ｗhen create table with invalid option, can't disconnect infinity.
`thrift.transport.TTransport.TTransportException: TSocket read 0 bytes`

### Steps to reproduce

```Markdown
Function test code can be found in python/test/test_create.py `test_table_with_different_invalid_options`
```

**Comment by JinHai-CN** [comment]
Fixed by #851
