### ISSUE TITLE
[Bug]: Topn option in knn function cause core dumped.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#776]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

7257da2

### Actual behavior

use `0`
`ERROR: AddressSanitizer: heap-buffer-overflow on address 0x502000009bf0 at pc 0x5bdb2772d2a4 bp 0x7d8ea9efc9d0 sp 0x7d8ea9efc9c8`
use`-1`
`exceeds maximum supported size of 0x10000000000`

### Steps to reproduce

```Markdown
Function test case can be found in python/test/test_knn.py `test_various_topn`
please use such as `0`, `-1` topn to reproduce the bugs.
```

**Comment by Ognimalf** [comment]
Fixed.
