### ISSUE TITLE
[Bug]: confusing recall rate displayed in benchmark result

### ISSUE THREAD

**Issue by morphes1995** [infiniflow/infinity#796]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

e85d1924

### Actual behavior

Recall rate is always 0 in case of using single thread to execute the benchmark test
```shell
Single-thread
Rounds: 1
Round 1:
Total Dur: 10.94 s
Query Count: 10000
QPS: 914.00
Recall@1: 0.0
Recall@10: 0.0
Recall@100: 0.0
``` 

And Recall rate reports is missing when using multiple threads
```shell
Multi-threads: 2
Rounds: 1
Total Query Count: 1000
Round 1:
Total Dur: 1.24 s
Query Count: 1000
QPS: 809.33
``` 

### Steps to reproduce

```Markdown
python3 remote_benchmark_knn.py -t 2 -r 1 -d gist_1m
```

**Comment by JinHai-CN** [comment]
For multi-threads, the benchmark won't calculate the recall rate, since it use the same way to search the database. As for the single-thread, #799 will fix it.

**Comment by morphes1995** [comment]
> For multi-threads, the benchmark won't calculate the recall rate, since it use the same way as 'single thread mode' to search the database. As for the single-thread, #799 will fix it.

yeh, used wrong field when parse query result
```python
query_results[idx].append(res_list[j][0])
```

**Comment by JinHai-CN** [comment]
Fixed.
