### ISSUE TITLE
[Question]: Is there any good first issues  that is suitable for the beginners ?

### ISSUE THREAD

**Issue by morphes1995** [infiniflow/infinity#805]
### Describe your problem

Is there any good first issues , documentations or source code analysis blogs that help beginners to have a deep dive

**Comment by JinHai-CN** [comment]
The current project is still in the first release stage of development, and there may not be the article you need to describe the internal details. It is recommended to understand the internal logic of an API or SQL entry based on the read or write process. For beginners, there are two directions to consider.

1. We are developing C++ SDK, HTTP API and HTTPS supporting, you may choose one or two APIs to implement.
2. Some issues such as #775 may be may suitable for beginners.

In this week, we have an meeting to share the architecture of the system. If you are interested in, you can send an email to haijin.chn@gmail.com.
