### ISSUE TITLE
[Bug]: Invalid parameters in match function, the teardown error occurs.

### ISSUE THREAD

**Issue by chrysanthemum-boy** [infiniflow/infinity#919]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ef01518

### Actual behavior

When using invalid parameters in match function, the teardown error occurs and can't shutdown infinity.
`thrift.transport.TTransport.TTransportException: TSocket read 0 bytes`
`../../../miniconda3/envs/infinity_test/lib/python3.10/site-packages/thrift/transport/TSocket.py:166: TTransportException`

### Steps to reproduce

```Markdown
Function test code can be found in python/test/test_knn.py 
`test_with_fulltext_match_with_columns`
`test_with_fulltext_match_with_words`
`test_with_fulltext_match_with_options`
```

**Comment by Ognimalf** [comment]
Fixed by #920 .
