### ISSUE TITLE
[Bug]: Infinity cannot quit on SIGTERM if there are some alive client sessions

### ISSUE THREAD

**Issue by yuzhichang** [infiniflow/infinity#940]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

092c19a9734f75bd44333a00e74ad7f48cbdec16

### Actual behavior

Infinity cannot quit on SIGTERM if there are some alive client sessions

### Expected behavior

Infinity shall quit on SIGTERM no matter the client sessions.

### Steps to reproduce

```Markdown
- Start infinity db at terminal 1.
- Connect it with `psql` at terminal 2.
- Type Ctrl-C at terminal 1. The infinity cannot quit.
- Kill the `psql` at terminal 2.
```

**Comment by JinHai-CN** [comment]
This behavior is by design.
