### ISSUE TITLE
[Feature Request]: Import JSON file

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#945]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Currently, Infinity supports import JSONL file. But importing JSON file isn't implemented. Like JSONL parsing, JSON file importing can also use nlohmann::json to parsing the json string.

### Documentation, adoption, use case

sqllogictest, python test, http test cases also need to implemented.

**Comment by PandaWannaSleep** [comment]
Hi, can I take this issue and make contributions to it?
