### ISSUE TITLE
[Subtask]: Implement ElasticSearch client

### ISSUE THREAD

**Issue by yangjie407** [infiniflow/infinity#954]
### Parent Issue

Parent issue: #951

### Detail of Subtask

The ElasticSearch client is inherited from BaseClient, and implements the functions(upload, search) using ElasticSearch python SDK.

**Comment by Rassyan** [comment]
I'm interested in the performance comparison between Infinity and ES. Is external contribution needed for this issue?

**Comment by JinHai-CN** [comment]
@Rassyan Qdrant client is implemented. #969
