### ISSUE TITLE
Column whose `DataType` is `Varchar`, default `dimension` = 0

### ISSUE THREAD

**Issue by KKould** [infiniflow/infinity#96]
#### What happens?
default dimension of `VarcharInfo` should not be 0

src/planner/logical_planner.cpp `LogicalPlanner::BuildInsertValue`
![image](https://github.com/infiniflow/infinity/assets/91525956/9625efbb-5eee-4b4c-95f4-2f156ac72375)

#### To Reproduce
``` sql
create table t3 (a int primary key, z varchar unique null);

insert into t3 (a, z) values (1, 'k');
```

#### Environment (please complete the following information):
- Ubuntu 12.3.0-1ubuntu1~23.04
- infinity Version: 0.0.1
- infinity Client: PG-Client

#### Before Submitting

- [x] **Have you tried this on the latest `main` branch?**
- [x] **Give your commit id** [7e69246](https://github.com/infiniflow/infinity/commit/7e69246e74390297bbfd860650666e1ae6a30581)
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by JinHai-CN** [comment]
Fixed
