### ISSUE TITLE
[Bug]: List databases crash when databases count large than 8192

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#961]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

7147a847db41ebdb01714d6b8f10bed5b3cc73bb

### Actual behavior

Infinity crash since the vector size is more than 8192, exceed the capacity.

### Steps to reproduce

```Markdown
1. Create too many databases, more than 8192. (run case: test_create_drop_show_1M_databases, cancel the case running before it finished)
2. List databases.
3. Crash since the vector size is more than 8192, exceed the capacity.
```

**Comment by colommar** [comment]
Hello, I'm a newbie in the community and I'd like to try this issue, I understand that it's a crash caused by overrunning the capacity when creating a large database, but I don't have the slightest clue as to how to solve the problem, I wonder if you could give some advice?

**Comment by JinHai-CN** [comment]
Firstly, I am very pleased that you are interested in this project and issue.

The transfer of data between Infinity operators is done through structure DataBlock. And DataBlock is composed of multiple columns, with each column being a data structure called ColumnVector. For the ListDatabase operation, it is to put the names of all databases in the current database into ColumnVector, and then form a DataBlock to return.

The current issue is that each ColumnVector has 8192 rows of data, which means each DataBlock has 8192 rows. If the number of databases obtained by ListDatabase operation exceeds 8192 rows, the ColumnVector cannot hold them, which will trigger a crash.

In this case, we can use multiple DataBlocks, that is, multiple ColumnVectors, to contain the results of the ListDatabase operation. That is to say, as soon as we reach row count 8192, we will create another ColumnVector/DataBlock to hold more data.

The location of the ListDatabase code is in: PhysicalShow. cpp: L341, which is the PhysicalShow:: ExecuteShowDatabases method.

In terms of implementation, we may need to introduce an IsFull check in the class of ColumnVector or DataBlock to determine that the current ColumnVector/DataBlock is full. This makes it convenient for us to create a new ColumnVector/DataBlock in PhysicalShow:: ExecuteShowDatabases to load the new data.

The above is the relevant information about this bug, hoping to be helpful to you.

**Comment by colommar** [comment]
Thank you very much for your reply, but I think, I should try to reproduce the problem first, I successfully created 8193 databases by using the following codes.
```bash
HOST="localhost"
PORT="5432"
USER="your_username"
DATABASE="postgres" 
for i in {1..8193}
do
    DB_NAME="database_$i"
    echo "Creating database: $DB_NAME"
    PGPASSWORD=your_password psql -h "$HOST" -p "$PORT" -U "$USER" -d "$DATABASE" -c "CREATE DATABASE \"$DB_NAME\";"
done

echo "Done creating databases."

```
But there are some problems when enumerating the databases, I use `\l` as well as `SELECT datname FROM pg_database;` both are unsuccessful, can I trouble you to give some suggestions?

**Comment by JinHai-CN** [comment]
Although the SQL interface of infinity uses the PG protocol, it has not been fully implemented and can only be accessed through the command line. And infinity is not a database system implemented based on PG. So, there is no catalog like pg_database.

Currently, it is recommended to use the [Python SDK API](https://github.com/infiniflow/infinity/blob/main/docs/references/pysdk_api_reference.md) and [REST API](https://github.com/infiniflow/infinity/blob/main/docs/references/http_api_reference.md) to access infinity.

Meanwhile, you can also refer to [test database cases](https://github.com/infiniflow/infinity/blob/6a4227affc665fba9bd012306669099d821880fa/python/test/test_database.py#L163C9 -L163C43)

**Comment by colommar** [comment]
Thanks for the reply. I will try this problem next week cause I have a test on Saturday. :)
> Although the SQL interface of infinity uses the PG protocol, it has not been fully implemented and can only be accessed through the command line. And infinity is not a database system implemented based on PG. So, there is no catalog like pg_database.
> 
> 
> 
> Currently, it is recommended to use the [Python SDK API](https://github.com/infiniflow/infinity/blob/main/docs/references/pysdk_api_reference.md) and [REST API](https://github.com/infiniflow/infinity/blob/main/docs/references/http_api_reference.md) to access infinity.
> 
> 
> 
> Meanwhile, you can also refer to [test database cases](https://github.com/infiniflow/infinity/blob/main/python/test/test_database.py#L163)

**Comment by JinHai-CN** [comment]
> Thanks for the reply. I will try this problem next week cause I have a test on Saturday. :)
> > Although the SQL interface of infinity uses the PG protocol, it has not been fully implemented and can only be accessed through the command line. And infinity is not a database system implemented based on PG. So, there is no catalog like pg_database.
> > 
> > 
> > 
> > Currently, it is recommended to use the [Python SDK API](https://github.com/infiniflow/infinity/blob/main/docs/references/pysdk_api_reference.md) and [REST API](https://github.com/infiniflow/infinity/blob/main/docs/references/http_api_reference.md) to access infinity.
> > 
> > 
> > 
> > Meanwhile, you can also refer to [test database cases](https://github.com/infiniflow/infinity/blob/main/python/test/test_database.py#L163)
> 
> 

Good luck.

**Comment by Ognimalf** [comment]
@colommar still working on it? Otherwise I will take it.

**Comment by colommar** [comment]
> @colommar still working on it? Otherwise I will take it.

Nope, I was quite busy these days...
