### ISSUE TITLE
[Bug]: Incorrect COUNT(*) result in big dataset.

### ISSUE THREAD

**Issue by Ognimalf** [infiniflow/infinity#962]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

00f919b

### Actual behavior

When import a 1m file, the result of  `count(*)`  is wrong, and the max result is always 131072(which equals to the size of 16 full block).

The result in psql as follows:
```
xwg=> CREATE TABLE test (id VARCHAR, title VARCHAR, text VARCHAR);
COPY test FROM '/home/xwg/dev/infinity/test/data/jsonl/1m.jsonl' WITH (FORMAT JSONL);
 OK 
----
(0 rows)

IMPORT 1000000 Rows
xwg=> select count(*) from test;
 count(star) 
-------------
      131072
(1 row)
```

And the service log:
```
[20:05:18.379] [1037591] [info] Block 0 saved
[20:05:18.403] [1037591] [info] Block 1 saved
[20:05:18.427] [1037591] [info] Block 2 saved
...
[20:05:21.280] [1037591] [info] Block 119 saved
[20:05:21.305] [1037591] [info] Block 120 saved
[20:05:21.330] [1037591] [info] Block 121 saved
```

### Steps to reproduce

```Markdown
CREATE TABLE test (id VARCHAR, title VARCHAR, text VARCHAR);
COPY test FROM '/home/xwg/dev/infinity/test/data/jsonl/1m.jsonl' WITH (FORMAT JSONL);
select count(*) from test;
```

**Comment by JinHai-CN** [comment]
#974 is the workaround solution.

The solution in the plan is to independently calculate the count value for each task, and each task needs to materialize the results. When the results of each task are all calculated and materialized, the data will be sent to the merge aggregate operator for calculation to obtain the final result. This can also save data transmission between different fragments.
The main areas that need to be modified are focused on the calculation of expressions, and the current expression calculation does not support the above solution.

**Comment by Ognimalf** [comment]
#1027 fix the incorrect implementation of aggregation.
