### ISSUE TITLE
An exception occurred while Insert string into column whose `DataType` is `Varchar`

### ISSUE THREAD

**Issue by KKould** [infiniflow/infinity#98]
#### What happens?
I created a table with a Varchar field and inserted a string into the corresponding field before an exception occurred
![image](https://github.com/infiniflow/infinity/assets/91525956/aee73c37-0e59-4225-9673-ca9713550b12)

Tips: src/function/cast/varchar_cast.h:47
#### To Reproduce
``` sql
create table t7 (a int primary key, z varchar(298) unique null);

insert into t7 (a, z) values (1, 'k');
```

#### Environment (please complete the following information):
- Ubuntu 12.3.0-1ubuntu1~23.04
- infinity Version: 0.0.1
- infinity Client: PG-Client

#### Before Submitting

- [x] **Have you tried this on the latest `main` branch?**
- [x] **Give your commit id** [7e69246](https://github.com/infiniflow/infinity/commit/7e69246e74390297bbfd860650666e1ae6a30581)
- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by JinHai-CN** [comment]
Fixed
