### ISSUE TITLE
[Bug]: server crash when importing files lots of times, to build vector index. Invalid MergeFlag from 1 to 3@src/storage/wal/catalog_delta_entry.cpp:182

### ISSUE THREAD

**Issue by Ziyan2019** [infiniflow/infinity#997]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8702dae

### Actual behavior

terminate called after throwing an instance of 'infinity::UnrecoverableException@infinity_exception'
  what():  Invalid MergeFlag from 1 to 3@src/storage/wal/catalog_delta_entry.cpp:182

### Steps to reproduce

```Markdown
run: pytest -k test_vector_index_single_thread python/test (add -s to print)
```

**Comment by small-turtle-1** [comment]
duplicate with #991
