### ISSUE TITLE
[Bug]: Deadlock, "Error: SEGMENT FAULTS", "Cannot find block segment id: 17, block id: 0@src/executor/operator/physical_knn_scan.cpp:542"

### ISSUE THREAD

**Issue by Ziyan2019** [infiniflow/infinity#999]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8702dae

### Actual behavior

three types of bugs occur, which are 
1. deadlock, 
2. "Error: SEGMENT FAULTS", 
3. "Cannot find block segment id: 17, block id: 0@src/executor/operator/physical_knn_scan.cpp:542". 
Besides the bug occur in single thread : " Invalid MergeFlag from 1 to 3@src/storage/wal/catalog_delta_entry.cpp:182"

### Steps to reproduce

```Markdown
run: pytest -k test_vector_index_rw_parallel python/test (add -s to print)
```

**Comment by JinHai-CN** [comment]
Fixed by #1056
